version: '2'

services:
  server:
    image: golang:1.17
    restart: always
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=max
      - CASSANDRA_PASSWORD=password
    volumes:
      - ./src:/app
    working_dir: /app
    command: go run main.go
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/bitnami
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=max
      - CASSANDRA_PASSWORD=password
volumes:
  cassandra_data:
    driver: local